### ISSUE TITLE
Constantly getting Error in log

### ISSUE THREAD

**Issue by schlotz** [ToddGreenfield/homebridge-directv#19]
[8/25/2021, 8:44:13 AM] [homebridge-directv] This plugin generated a warning from the characteristic 'Channel': characteristic was supplied illegal value: number 0 exceeded minimum of 1. See https://git.io/JtMGR for more info.

Can we get this fixed somehow?

**Comment by apexad** [comment]
should be fixed in 1.0.5

**Comment by dkahia** [comment]
I am still getting this error. Do I need to make any adjustments for it to go away?
